- name: Get Disks
  ansible.builtin.include_tasks:
    file: get_disks.yml
  tags:
    - get_disks
    - generate_host_vars

- name: Generate Host Vars Template
  ansible.builtin.include_tasks:
    file: generate_host_vars_template.yml
  tags:
    - generate_host_vars
    - never
  when: "'generate_host_vars' in ansible_run_tags" # Only run when 'generate_host_vars' is included in the tags, to prevent accidental execution

- name: Provision Disks
  ansible.builtin.include_tasks:
    file: provision_disks.yml
  tags:
    - provision_disks
